#### inside "pyfli.__init__.py"
__version__ = "0.1.17"

# Pulling everything from the scripts gatekeeper
from .scripts import (DataOperations, IRFAligner, DataViewer,
                        AlliGprocessedImport, BHprocessedImport, PyFliprocessedImport,
                        HardSimulator, HardestSimulator, DatasetPlotter,
                        PhasorAnalyzer,
                        Plotter, DLModelComparator, DataPreprocessing,
                        PlotConfig, DataProcessor, SourceLoader, PlotKit, SubplotVisualizer, plot_2d_subplots,
                        BaseFLIFitter, Fli_CPUProcessor, Fli_GPUProcessor, MLEFLIFitter,
                        GlobalFLIFitter, ROIMaker, AnalyticalHelpers, DataIO_utils, Colorprocess,
                        Macro_sim, TCSPC_sim, FLIImageGenerator, FLICalibrator, FLIValidator, Normalization,
                        recovery_plot, random_true_pixel, data_masking, save_plot,
                        Msg_display, FittingComparator, Detector,
                        BinnedFliFitter, FliBinner, ROIoperations, Batch_sim, DataSaver,
                        load_flim_data, collapse_to_xyt, plot_xyt,
                        LaguerreFLI, plot_pixel_diagnostic, compute_detailed_results, MonoBiClassifier, ParamCorrelationMatrix,
                        AcquisitionConfig, AcquisitionMode,
                        phasor_continuous, phasor_discrete, phasor_gated_single, phasor_gated_N,
                        phasor_truncated, phasor_offset, phasor_from_config,
                        build_locus, build_loci, tau_grid, universal_semicircle, sepl_center_radius_discrete,
                        phase_lifetime, modulus_lifetime, lifetime_from_phasor,
                        phase_lifetime_gated, fractional_components,
                        plot_phasor, plot_locus_comparison, plot_discrete_N_sweep,
                        load_session_arrays, scan_session_results, load_fitting_results,
                        inject_phasor_result, add_mean_lifetime,
                        compute_freq_axis, compute_phasor, plot_phasor_figures, save_phasor_result,
                        plot_fitting_maps, plot_diagnostics, plot_pixel_evidence,
                        plot_statistical_comparison, plot_2d_analysis,
                        run_mono_bi_classifier,
                        FBI_RESULT_FILENAME, FBI_RAW_FILENAME)

from .spAnalysis import (BasisPatterns, MeasurementSimulator, Reconstructor)
from ._logo import pflogo

__all__ = ['DataOperations', 'IRFAligner', 'DataViewer', 
        'AlliGprocessedImport', 'BHprocessedImport', 'PyFliprocessedImport', 
        'HardSimulator', 'HardestSimulator', 'DatasetPlotter',
        'PhasorAnalyzer',
        'Plotter', 'DLModelComparator', 'DataPreprocessing', 
        'BaseFLIFitter', 'Fli_CPUProcessor', 'Fli_GPUProcessor', 
        'MLEFLIFitter', 'GlobalFLIFitter', 'ROIMaker', 
        'AnalyticalHelpers', 'DataIO_utils',
        'Colorprocess', 'Macro_sim', 'TCSPC_sim', 'FLIImageGenerator', 
        'recovery_plot', 'random_true_pixel', 'save_plot',
        'FLICalibrator', 'FLIValidator', 'Normalization',
        'Msg_display', 'FittingComparator',
        'data_masking', 'Detector', 'BinnedFliFitter', 'FliBinner',
        'ROIoperations', 'Batch_sim', 'DataSaver', 'LaguerreFLI',
        'PlotConfig', 'DataProcessor', 'SourceLoader', 'PlotKit', 'SubplotVisualizer', 
        'plot_2d_subplots', 'plot_pixel_diagnostic', 'compute_detailed_results',
        'MonoBiClassifier', 'ParamCorrelationMatrix',
        # phasor module
        'AcquisitionConfig', 'AcquisitionMode',
        'phasor_continuous', 'phasor_discrete', 'phasor_gated_single', 'phasor_gated_N',
        'phasor_truncated', 'phasor_offset', 'phasor_from_config',
        'build_locus', 'build_loci', 'tau_grid', 'universal_semicircle', 'sepl_center_radius_discrete',
        'phase_lifetime', 'modulus_lifetime', 'lifetime_from_phasor',
        'phase_lifetime_gated', 'fractional_components',
        'plot_phasor', 'plot_locus_comparison', 'plot_discrete_N_sweep',
        # this is for SPAnalysis
        'BasisPatterns', 'MeasurementSimulator', 'Reconstructor',
        'load_flim_data', 'collapse_to_xyt', 'plot_xyt',
        # analysis convenience functions
        'load_session_arrays', 'scan_session_results', 'load_fitting_results',
        'inject_phasor_result', 'add_mean_lifetime',
        'compute_freq_axis', 'compute_phasor', 'plot_phasor_figures', 'save_phasor_result',
        'plot_fitting_maps', 'plot_diagnostics', 'plot_pixel_evidence',
        'plot_statistical_comparison', 'plot_2d_analysis',
        'run_mono_bi_classifier',
        'FBI_RESULT_FILENAME', 'FBI_RAW_FILENAME',
        'pflogo',
        ]

