# simulator/calibration_engine.py
"""Hardware-noise calibration engine for the FLI simulator.

Provides ``FLICalibrator``, which fits simulator noise parameters (dark
count rate, read noise, intensity scale) so that simulated decay cubes
statistically match an experimental reference decay cube, using
``scipy.optimize.minimize`` against a KS-test/histogram-intersection loss
computed by ``FLIValidator``.
"""
import numpy as np
import json
import os
from scipy import stats
from scipy.optimize import minimize
import matplotlib.pyplot as plt
from .sim_image_generator import FLIImageGenerator
from .sim_stat_test import FLIValidator

class FLICalibrator:
    """Calibrates simulator hardware-noise parameters against real data.

    Optimizes DCR, read noise sigma, and an intensity/photon-count scale
    parameter so that images generated by ``FLIImageGenerator`` statistically
    match an experimental decay cube, as scored by ``FLIValidator``.
    """

    def __init__(self, irf_data, method='analytical', threshold=10, normalize_stats=False):
        """Initializes the calibrator.

        Args:
            irf_data: IRF data (1-D trace or 3-D IRF stack) passed through
                to ``FLIImageGenerator`` during calibration.
            method: Simulation method, e.g. ``'analytical'`` or ``'tcspc'``
                (lower-cased and forwarded to ``FLIImageGenerator`` and
                ``FLIValidator``).
            threshold: Minimum integrated photon count for a pixel to be
                considered valid, forwarded to ``FLIValidator``.
            normalize_stats: If True, normalizes simulated/experimental
                intensity distributions to [0, 1] before comparison (see
                ``FLIValidator.run_comprehensive_test``).
        """
        self.irf_data = irf_data
        self.method = method.lower()
        self.threshold = threshold
        self.normalize_stats = normalize_stats
        self.validator = FLIValidator(method=self.method, threshold=self.threshold)
        self.iteration = 0
        self.opt_params = None

    def _get_valid_counts(self, data_cube):
        _, counts = self.validator._preprocess_cube(data_cube)
        return counts

    def objective_function(self, x, exp_decay_cube, base_cfg):
        """Loss function minimized during calibration.

        Builds a simulator config from the candidate parameter vector,
        generates a simulated dataset, and scores it against the
        experimental decay cube.

        Args:
            x: Candidate parameter vector ``[dcr, read_sigma,
                intensity_alpha]``.
            exp_decay_cube: Experimental reference decay cube to match.
            base_cfg: Base simulator config dict to copy and override with
                the candidate ``dcr``/``read_sigma``/photon-count-alpha
                values before generating the simulated image.

        Returns:
            float: ``(1 - ks_p_value) + (1 - hist_intersection)`` for the
            candidate parameters, or ``2.0`` (worst-case) if validation
            fails or raises an exception.
        """
        self.iteration += 1
        current_cfg = base_cfg.copy()
        
        # x = [DCR, Read_Sigma, Intensity_Alpha]
        current_cfg['dcr'] = x[0]
        current_cfg['read_sigma'] = x[1]
        
        pc_key = 'pc' if 'pc' in base_cfg else 'photo_count'
        orig_pc = list(base_cfg.get(pc_key, (8, 2)))
        current_cfg[pc_key] = (x[2], orig_pc[1])

        gen = FLIImageGenerator(self.irf_data, image_shape=(32, 32), 
                                roi_params=[current_cfg], method=self.method,
                                verbose=False)
        sim_dataset = gen.generate_image()

        try:
            results = self.validator.run_comprehensive_test(
                sim_dataset, exp_decay_cube, normalize=self.normalize_stats
            )
            if results is None: return 2.0
            
            p_val = results['ks_p_value']
            loss = (1.0 - p_val) + (1.0 - results['hist_intersection'])
            return loss
        except Exception:
            return 2.0

    def display_report(self, results):
        """Prints a validation metrics summary and plots comparison figures.

        Displays a text table of cosine similarity, KL divergence, KS
        p-value, and histogram intersection, then plots the mean temporal
        decay profiles and integrated-intensity PDFs for simulated vs.
        experimental data.

        Args:
            results: Metrics dict as returned by
                ``FLIValidator.run_comprehensive_test``, or None (in which
                case only a "No results" message is printed).
        """
        if results is None:
            print("No results to display.")
            return

        print("\n" + "="*60)
        print(f"STATISTICAL VALIDATION REPORT (N={results['sample_size']} Pixels)")
        print("="*60)
        print(f"{'Metric':<25} | {'Value':<15} | {'Target'}")
        print("-" * 60)
        print(f"{'Cosine Similarity':<25} | {results['cosine_similarity']:<15.4f} | >0.99")
        print(f"{'KL Divergence':<25} | {results['kl_divergence']:<15.4f} | <0.01")
        print(f"{'KS P-Value':<25} | {results['ks_p_value']:<15.4e} | >0.05")
        print(f"{'Hist Intersection':<25} | {results['hist_intersection']:<15.4f} | -> 1.0")
        print("="*60 + "\n")

        fig, axes = plt.subplots(1, 2, figsize=(15, 5))
        
        axes[0].plot(results['sim_vec'], label='Simulated (Mean)', lw=2)
        axes[0].plot(results['exp_vec'], label='Experimental (Mean)', ls='--', lw=2)
        axes[0].set_yscale('log')
        axes[0].set_title("Temporal Profile Fidelity")
        axes[0].set_xlabel("Time Bin")
        axes[0].set_ylabel("Normalized Intensity")
        axes[0].grid(True, which='both', alpha=0.3)
        axes[0].legend()

        axes[1].hist(results['sim_counts'], bins=50, alpha=0.5, label='Simulated', density=True, color='tab:blue')
        axes[1].hist(results['exp_counts'], bins=50, alpha=0.5, label='Experimental', density=True, color='tab:orange')
        axes[1].set_title("Integrated Intensity PDF")
        axes[1].set_xlabel("Photon Counts (Integrated)")
        axes[1].set_ylabel("Probability Density")
        axes[1].legend()
        
        plt.tight_layout()
        plt.show()

    def run_calibration(self, exp_decay_cube, base_config, initial_guess=None):
        """Fits DCR, read noise, and intensity scale to an experimental decay cube.

        Runs ``scipy.optimize.minimize`` (L-BFGS-B) on ``objective_function``
        to find the ``[dcr, read_sigma, intensity_alpha]`` triple that best
        matches ``exp_decay_cube``, then generates and displays a final
        calibration report.

        Args:
            exp_decay_cube: Experimental reference decay cube to calibrate
                against.
            base_config: Base simulator config dict; a copy is updated with
                the optimized parameters to build the final config.
            initial_guess: Optional initial ``[dcr, read_sigma,
                intensity_alpha]`` guess. If None, a guess is derived from
                the mean experimental photon counts (for ``'analytical'``
                method) or a fixed default, with ``dcr=0.01`` and
                ``read_sigma=1.2``.

        Returns:
            dict: The final calibrated simulator config (``base_config``
            updated with the optimized ``dcr``, ``read_sigma``, and photon
            count parameters).
        """
        print(f"--- Starting Calibration: {self.method.upper()} (Norm: {self.normalize_stats}) ---")
        self.iteration = 0
        
        pc_key = 'pc' if 'pc' in base_config else 'photo_count'
        _, exp_counts = self.validator._preprocess_cube(exp_decay_cube)
        
        if initial_guess is None:
            # Smart guess for intensity alpha based on mean counts
            rough_alpha = np.mean(exp_counts) / 10 if self.method == 'analytical' else 5.0
            initial_guess = [0.01, 1.2, rough_alpha]

        # REVISED BOUNDS: Lowered DCR max to 0.1 to prevent overfitting in low-signal regimes
        bounds = [(0, 0.1), (0, 10.0), (0.1, 1000.0)]
        
        res = minimize(self.objective_function, x0=initial_guess, 
                       args=(exp_decay_cube, base_config),
                       bounds=bounds, method='L-BFGS-B', tol=1e-2)

        self.opt_params = {
            'dcr': float(res.x[0]), 
            'read_sigma': float(res.x[1]),
            pc_key: (float(res.x[2]), float(base_config[pc_key][1]))
        }
        
        final_cfg = base_config.copy()
        final_cfg.update(self.opt_params)
        
        print("\nGenerating Final Optimized Calibration Report...")
        gen = FLIImageGenerator(self.irf_data, image_shape=(32, 32), 
                                roi_params=[final_cfg], method=self.method)
        final_sim = gen.generate_image()
        metrics = self.validator.run_comprehensive_test(final_sim, exp_decay_cube, normalize=self.normalize_stats)
        self.display_report(metrics)
        
        return final_cfg

    def cross_validate(self, calibrated_cfg, test_exp_cube):
        """Validates a calibrated config against an unseen experimental cube.

        Generates a simulated dataset using ``calibrated_cfg`` (matching the
        shape of ``test_exp_cube``), scores it against ``test_exp_cube``, and
        displays the validation report.

        Args:
            calibrated_cfg: Simulator config to validate, typically the
                output of ``run_calibration``.
            test_exp_cube: Held-out experimental decay cube to validate
                against.

        Returns:
            dict: Metrics dict as returned by
            ``FLIValidator.run_comprehensive_test``.
        """
        print(f"\n--- Cross-Validation (Norm: {self.normalize_stats}) ---")
        gen = FLIImageGenerator(self.irf_data, image_shape=test_exp_cube.shape[:2], 
                                roi_params=[calibrated_cfg], method=self.method)
        sim_dataset = gen.generate_image()
        metrics = self.validator.run_comprehensive_test(sim_dataset, test_exp_cube, normalize=self.normalize_stats)
        self.display_report(metrics)
        return metrics

    def save_hardware_profile(self, filename="hw_profile.json"):
        """Saves the optimized calibration parameters to a JSON file.

        Args:
            filename: Destination path for the JSON profile file.

        Returns:
            None. Does nothing if calibration has not yet been run (i.e.
            ``self.opt_params`` is None).
        """
        if self.opt_params is None: return
        profile = {"method": self.method, "threshold": self.threshold, 
                   "normalize_used": self.normalize_stats, "params": self.opt_params}
        with open(filename, 'w') as f:
            json.dump(profile, f, indent=4)
        print(f"Profile saved to {filename}")

    @staticmethod
    def load_hardware_profile(filename):
        """Loads a previously saved hardware calibration profile.

        Args:
            filename: Path to a JSON profile file previously written by
                ``save_hardware_profile``.

        Returns:
            dict or None: The parsed profile dict, or None if ``filename``
            does not exist.
        """
        if not os.path.exists(filename): return None
        with open(filename, 'r') as f: return json.load(f)

    def plot_noise_sensitivity(self, train_exp_cube, base_config, dcr_range=(0.001, 0.1, 10), sigma_range=(0.5, 4.0, 10)):
        """Scans a DCR/read-noise grid and plots a KS p-value sensitivity map.

        For each combination of DCR and read-noise sigma on the given
        grids, simulates an image, compares its integrated photon counts to
        ``train_exp_cube`` via a two-sample KS test, and renders the
        resulting p-value surface as a heatmap (marking the current
        ``opt_params`` optimum, if any).

        Args:
            train_exp_cube: Experimental decay cube used as the KS-test
                reference.
            base_config: Base simulator config dict; ``dcr`` and
                ``read_sigma`` are overridden for each grid point.
            dcr_range: ``(start, stop, num)`` passed to ``np.linspace`` to
                build the DCR grid.
            sigma_range: ``(start, stop, num)`` passed to ``np.linspace``
                to build the read-noise-sigma grid.

        Returns:
            tuple: ``(fig, p_matrix)`` where ``fig`` is the matplotlib
            figure and ``p_matrix`` is a 2-D array of KS p-values indexed
            ``[dcr_index, sigma_index]``.
        """
        print("Generating Sensitivity Surface (Processing...)")
        dcr_vals = np.linspace(*dcr_range)
        sigma_vals = np.linspace(*sigma_range)
        p_matrix = np.zeros((len(dcr_vals), len(sigma_vals)))
        target_counts = self._get_valid_counts(train_exp_cube)

        for i, dcr in enumerate(dcr_vals):
            for j, sigma in enumerate(sigma_vals):
                cfg = base_config.copy()
                cfg['dcr'], cfg['read_sigma'] = dcr, sigma
                gen = FLIImageGenerator(self.irf_data, image_shape=(32, 32),
                                         roi_params=[cfg], 
                                         method=self.method, verbose = False)
                sim_data = gen.generate_image()
                sim_counts = self._get_valid_counts(sim_data['raw_data']['decay'])
                _, p_val = stats.ks_2samp(sim_counts, target_counts)
                p_matrix[i, j] = p_val

        fig, ax = plt.subplots(figsize=(9, 7))
        im = ax.imshow(p_matrix, extent=[sigma_vals[0], sigma_vals[-1], dcr_vals[0], dcr_vals[-1]],
                       origin='lower', aspect='auto', cmap='magma')
        fig.colorbar(im, ax=ax, label='KS P-Value')
        ax.set_xlabel('Read Noise Sigma')
        ax.set_ylabel('DCR')
        if self.opt_params:
            ax.scatter(self.opt_params['read_sigma'], self.opt_params['dcr'], color='cyan', marker='x', s=100, label='Optimal Point')
            ax.legend()
        plt.show()
        return fig, p_matrix